package org.drools.audit.agenda;

public enum AgendaEventLogType {
	MATCH_CREATED, MATCH_CANCELLED, BEFORE_MATCH_FIRED, AFTER_MATCH_FIRED,
	AGENDA_GROUP_POPPED, AGENDA_GROUP_PUSHED,
	RULEFLOW_GROUP_ACTIVATED, RULEFLOW_GROUP_DEACTIVATED;
}